<?php

/**
 * @file
 * Contains get_content.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function get_content_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the get_content module.
    case 'help.page.get_content':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Get content from other websites') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function get_content_theme() {
  return [
    'get_content' => [
      'template' => 'get_content',
      'render element' => 'children',
    ],
  ];
}
