fblikebutton.settings:
  type: mapping
  label: 'Facebook Like Button Settings'
  mapping:
    node_types:
      type: array
      label: 'Content types for the button'
    full_node_display:
      type: integer
      label: 'Option for the section where show the button'
    teaser_display:
      type: integer
      label: 'Option for the section where show the button or not show'
    iframe_width:
      type: integer
      label: 'Width of the iframe'
    iframe_height:
      type: integer
      label: 'Height of the iframe'
    iframe_css:
      type: string
      label: 'More css code to add to the iframe'
    layout:
      type: string
      label: 'Type of layout'
    show_faces:
      type: boolean
      label: 'Show faces'
    action:
      type: string
      label: 'Button action'
    font:
      type: string
      label: 'iframe font'
    color_scheme:
      type: string
      label: 'Color Scheme'
    weight:
      type: integer
      label: 'Field weight'
    language:
      type: string
      label: 'Language code'
